# Generated by Django 3.2.7 on 2021-09-20 10:35

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('acc_created_date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adres e-mail')),
                ('password', models.CharField(max_length=128, verbose_name='Hasło')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Użytkownik',
                'verbose_name_plural': 'Użytkownicy',
                'db_table': 'edziekanat_app_users',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Kierunek',
                'verbose_name_plural': 'Kierunki',
                'db_table': 'edziekanat_app_invoices_courses',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa instytutu')),
                ('location', models.CharField(max_length=100, verbose_name='Adres')),
                ('contact_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_decision_user', to=settings.AUTH_USER_MODEL, verbose_name='Osoba decyzyjna')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Kierownik instytutu')),
            ],
            options={
                'verbose_name': 'Instytut',
                'verbose_name_plural': 'Instytuty',
                'db_table': 'edziekanat_app_departments',
            },
        ),
        migrations.CreateModel(
            name='InvoiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa')),
                ('faq_link', models.URLField(blank=True, help_text='Link do regulaminu', verbose_name='Regulamin')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Opis')),
                ('docx_template', models.FileField(upload_to='edziekanat_app/invoice_templates', verbose_name='Plik wzorcowy')),
            ],
            options={
                'verbose_name': 'Kategoria wniosku',
                'verbose_name_plural': 'Kategorie wniosków',
                'db_table': 'edziekanat_app_invoices_categories',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Rola')),
            ],
            options={
                'verbose_name': 'Rola',
                'verbose_name_plural': 'Role',
                'db_table': 'edziekanat_app_roles',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=6, null=True)),
                ('sem', models.IntegerField(default=1, verbose_name='Semestr')),
                ('year', models.IntegerField(default=1, verbose_name='Rok')),
                ('degree', models.IntegerField(default=1, verbose_name='Stopień')),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='edziekanat_app.course', verbose_name='Kierunek')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Studenci',
                'db_table': 'edziekanat_app_students',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa instytutu')),
                ('location', models.CharField(max_length=100, verbose_name='Adres')),
                ('contact_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_decision_user', to=settings.AUTH_USER_MODEL, verbose_name='Osoba decyzyjna')),
                ('dean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dziekan')),
            ],
            options={
                'verbose_name': 'Wydział',
                'verbose_name_plural': 'Wydziały',
                'db_table': 'edziekanat_app_faculties',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
                'db_table': 'edziekanat_app_employees',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='deanery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziekanat_app.faculty', verbose_name='Wydział'),
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa instytutu')),
                ('location', models.CharField(max_length=100, verbose_name='Adres')),
                ('contact_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chair_decision_user', to=settings.AUTH_USER_MODEL, verbose_name='Osoba decyzyjna')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kierownik katedry')),
            ],
            options={
                'verbose_name': 'Katedra',
                'verbose_name_plural': 'Katedra',
                'db_table': 'edziekanat_app_chairs',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziekanat_app.role', verbose_name='Rola'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('ects', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziekanat_app.department', verbose_name='Instytut')),
            ],
            options={
                'verbose_name': 'Przedmiot',
                'verbose_name_plural': 'Przedmioty',
                'db_table': 'edziekanat_app_subjects',
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_file', models.FileField(upload_to='edziekanat_app/docs', verbose_name='Plik wniosku')),
                ('created_date', models.DateField(auto_now=True, verbose_name='Data utworzenia')),
                ('status', models.CharField(default='W trakcie', max_length=20, verbose_name='Status wniosku')),
                ('decision', models.CharField(blank=True, max_length=200, verbose_name='Decyzja')),
                ('decision_file', models.FileField(upload_to='edziekanat_app/docs', verbose_name='Plik decyzji')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziekanat_app.invoicecategory', verbose_name='Kategoria')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Wnioskodawca')),
                ('decision_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_authors', to=settings.AUTH_USER_MODEL, verbose_name='Osoba wyznaczona do dokonania decyzji')),
            ],
            options={
                'verbose_name': 'Wniosek',
                'verbose_name_plural': 'Wnioski',
                'db_table': 'edziekanat_app_invoices',
                'unique_together': {('created_by', 'category', 'created_date')},
            },
        ),
    ]
