# Generated by Django 3.2.7 on 2021-09-23 09:55

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import edziekanat_app.models.tables.invoice_category
import edziekanat_app.models.tables.subject
import edziekanat_app.models.tables.university_structure.department


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(default='Brak danych o numerze', max_length=9, verbose_name='Numer kontaktowy')),
                ('address', models.CharField(default='Brak danych', max_length=100, verbose_name='Adres zamieszkania')),
                ('acc_created_date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adres e-mail')),
                ('password', models.CharField(max_length=128, verbose_name='Hasło')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Użytkownik',
                'verbose_name_plural': 'Użytkownicy',
                'db_table': 'edziekanat_app_users',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa')),
                ('degree', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)], verbose_name='Stopień')),
            ],
            options={
                'verbose_name': 'Kierunek',
                'verbose_name_plural': 'Kierunki',
                'db_table': 'edziekanat_app_courses',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa instytutu')),
                ('location', models.CharField(max_length=100, verbose_name='Adres')),
                ('contact_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_decision_user', to=settings.AUTH_USER_MODEL, validators=[edziekanat_app.models.tables.university_structure.department.user_validator], verbose_name='Osoba decyzyjna')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, validators=[edziekanat_app.models.tables.university_structure.department.user_validator], verbose_name='Dyrektor instytutu')),
            ],
            options={
                'verbose_name': 'Instytut',
                'verbose_name_plural': 'Instytuty',
                'db_table': 'edziekanat_app_departments',
            },
        ),
        migrations.CreateModel(
            name='InvoiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Dziedzina wniosku',
                'verbose_name_plural': 'Dziedziny wniosków',
                'db_table': 'edziekanat_app_invoice_fields',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Stanowisko',
                'verbose_name_plural': 'Stanowiska',
                'db_table': 'edziekanat_app_jobs',
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Tryb',
                'verbose_name_plural': 'Tryby',
                'db_table': 'edziekanat_app_study_modes',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Rola')),
            ],
            options={
                'verbose_name': 'Rola',
                'verbose_name_plural': 'Role',
                'db_table': 'edziekanat_app_roles',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa')),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='edziekanat_app.course', verbose_name='Kierunek')),
            ],
            options={
                'verbose_name': 'Specjalizacja',
                'verbose_name_plural': 'Specjalizacje',
                'db_table': 'edziekanat_app_spectializations',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=6, null=True)),
                ('sem', models.IntegerField(default=1, verbose_name='Semestr')),
                ('year', models.IntegerField(default=1, verbose_name='Rok')),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='edziekanat_app.course', verbose_name='Kierunek')),
                ('specialization', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='edziekanat_app.specialization', verbose_name='Specjalizacja')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Studenci',
                'db_table': 'edziekanat_app_students',
            },
        ),
        migrations.CreateModel(
            name='InvoiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa')),
                ('faq_link', models.URLField(blank=True, help_text='Link do regulaminu', verbose_name='Regulamin')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Opis')),
                ('docx_template', models.FileField(upload_to='edziekanat_app/invoice_templates', validators=[edziekanat_app.models.tables.invoice_category.InvoiceCategory.validate_file_extension], verbose_name='Plik wzorcowy')),
                ('field_types', models.CharField(default='{}', editable=False, max_length=1000)),
                ('field', models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='edziekanat_app.invoicefield', verbose_name='Dziedzina')),
            ],
            options={
                'verbose_name': 'Kategoria wniosku',
                'verbose_name_plural': 'Kategorie wniosków',
                'db_table': 'edziekanat_app_invoice_categories',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa instytutu')),
                ('location', models.CharField(max_length=100, verbose_name='Adres')),
                ('contact_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_decision_user', to=settings.AUTH_USER_MODEL, verbose_name='Osoba decyzyjna')),
                ('dean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dziekan')),
            ],
            options={
                'verbose_name': 'Wydział',
                'verbose_name_plural': 'Wydziały',
                'db_table': 'edziekanat_app_faculties',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bosses', to=settings.AUTH_USER_MODEL, verbose_name='Przełożony')),
                ('job', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='edziekanat_app.job', verbose_name='Stanowisko')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
                'db_table': 'edziekanat_app_employees',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='deanery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deaneries', to='edziekanat_app.faculty', verbose_name='Wydział'),
        ),
        migrations.AddField(
            model_name='course',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziekanat_app.mode', verbose_name='tryb'),
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa instytutu')),
                ('location', models.CharField(max_length=100, verbose_name='Adres')),
                ('contact_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chair_decision_user', to=settings.AUTH_USER_MODEL, verbose_name='Osoba decyzyjna')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kierownik katedry')),
            ],
            options={
                'verbose_name': 'Katedra',
                'verbose_name_plural': 'Katedra',
                'db_table': 'edziekanat_app_chairs',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administratorzy',
                'db_table': 'edziekanat_app_administrators',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziekanat_app.role', verbose_name='Rola'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('ects', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziekanat_app.department', verbose_name='Instytut')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edziekanat_app.employee', validators=[edziekanat_app.models.tables.subject.Subject.user_validator], verbose_name='Prowadzący')),
            ],
            options={
                'verbose_name': 'Przedmiot',
                'verbose_name_plural': 'Przedmioty',
                'db_table': 'edziekanat_app_subjects',
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_file', models.FileField(upload_to='edziekanat_app/docs', verbose_name='Plik wniosku')),
                ('created_date', models.DateField(auto_now=True, verbose_name='Data utworzenia')),
                ('status', models.CharField(default='W trakcie', max_length=20, verbose_name='Status wniosku')),
                ('decision', models.CharField(blank=True, max_length=200, verbose_name='Decyzja')),
                ('decision_file', models.FileField(upload_to='edziekanat_app/docs', verbose_name='Plik decyzji')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziekanat_app.invoicecategory', verbose_name='Kategoria')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Wnioskodawca')),
                ('decision_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_authors', to=settings.AUTH_USER_MODEL, verbose_name='Osoba wyznaczona do dokonania decyzji')),
            ],
            options={
                'verbose_name': 'Wniosek',
                'verbose_name_plural': 'Wnioski',
                'db_table': 'edziekanat_app_invoices',
                'unique_together': {('created_by', 'category', 'created_date')},
            },
        ),
    ]
