# Generated by Django 3.2.7 on 2021-09-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edziekanat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='edziekanat_app_courses',
        ),
    ]
