# Generated by Django 3.2.6 on 2021-09-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edziekanat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmore',
            name='make',
        ),
        migrations.RemoveField(
            model_name='studentmore',
            name='model',
        ),
        migrations.RemoveField(
            model_name='studentmore',
            name='year',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
