# Generated by Django 3.2.7 on 2021-09-21 17:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edziekanat_app', '0003_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Dziedzina wniosku',
                'verbose_name_plural': 'Dziedziny wniosków',
                'db_table': 'edziekanat_app_invoice_fields',
            },
        ),
        migrations.AlterModelTable(
            name='invoicecategory',
            table='edziekanat_app_invoice_categories',
        ),
        migrations.AddField(
            model_name='invoicecategory',
            name='field',
            field=models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='edziekanat_app.invoicefield', verbose_name='Dziedzina'),
        ),
    ]
